name: Ejecutar tours automatizados
on:
  # workflow_dispatch:
  # push:
    # branches: [main]
  schedule:
    #- cron: '0  18 * * 3'
    - cron: '30 22 * * 5'
permissions:
  contents: write

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
          
      - name: Instalar dependencias
        run: pip install -r ../requirements.txt
        
      - name: Ejecutar script principal
        run: python main.py
        env:
          MODO_ALMACENAMIENTO: ${{ secrets.MODO_ALMACENAMIENTO }}
          HUBSPOT_TOKEN: ${{ secrets.HUBSPOT_TOKEN }}
          FORM_ID: ${{ secrets.FORM_ID }}
          CREDENCIAL_GOOGLE: ${{ secrets.CREDENCIAL_GOOGLE }}
          USUARIO: ${{ secrets.USUARIO }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECEPTORES: ${{ secrets.RECEPTORES }}
          SERVIDOR: ${{ secrets.SERVIDOR }}
          PUERTO: ${{ secrets.PUERTO }}
